name: simple
description: "A lightweight Flutter package for simplifying UI development"
version: 0.0.1
homepage: https://github.com/codingmitra/simple.git

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter: